[package]
name = "cc_gui"
version = "0.1.0"
authors = ["jonduvnjak <jon.duvnjak@volumental.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.2"
egui_glium = "0.2"
serde = "1"
